-- MySQL Script generated by MySQL Workbench
-- Fri May 31 03:58:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema student_management_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema student_management_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `student_management_database` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `student_management_database` ;

-- -----------------------------------------------------
-- Table `student_management_database`.`app_customuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`app_customuser` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `first_name` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME(6) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `user_type` VARCHAR(1) NOT NULL,
  `gender` VARCHAR(1) NOT NULL,
  `profile_pic` VARCHAR(100) NOT NULL,
  `address` LONGTEXT NOT NULL,
  `fcm_token` LONGTEXT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`app_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`app_admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `admin_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `admin_id` (`admin_id` ASC) VISIBLE,
  CONSTRAINT `app_admin_admin_id_6a28a365_fk_app_customuser_id`
    FOREIGN KEY (`admin_id`)
    REFERENCES `student_management_database`.`app_customuser` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`app_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`app_session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_year` DATE NOT NULL,
  `end_year` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`app_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`app_course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`app_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`app_staff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `admin_id` INT NOT NULL,
  `course_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `admin_id` (`admin_id` ASC) VISIBLE,
  INDEX `app_staff_course_id_7ff7285c_fk_app_course_id` (`course_id` ASC) VISIBLE,
  CONSTRAINT `app_staff_admin_id_44aabcdd_fk_app_customuser_id`
    FOREIGN KEY (`admin_id`)
    REFERENCES `student_management_database`.`app_customuser` (`id`),
  CONSTRAINT `app_staff_course_id_7ff7285c_fk_app_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `student_management_database`.`app_course` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`app_subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`app_subject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `course_id` INT NOT NULL,
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `app_subject_course_id_895f8ed2_fk_app_course_id` (`course_id` ASC) VISIBLE,
  INDEX `app_subject_staff_id_ba4d423b_fk_app_staff_id` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `app_subject_course_id_895f8ed2_fk_app_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `student_management_database`.`app_course` (`id`),
  CONSTRAINT `app_subject_staff_id_ba4d423b_fk_app_staff_id`
    FOREIGN KEY (`staff_id`)
    REFERENCES `student_management_database`.`app_staff` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`app_attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`app_attendance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `session_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `app_attendance_session_id_db88754c_fk_app_session_id` (`session_id` ASC) VISIBLE,
  INDEX `app_attendance_subject_id_a291fb2c_fk_app_subject_id` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `app_attendance_session_id_db88754c_fk_app_session_id`
    FOREIGN KEY (`session_id`)
    REFERENCES `student_management_database`.`app_session` (`id`),
  CONSTRAINT `app_attendance_subject_id_a291fb2c_fk_app_subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `student_management_database`.`app_subject` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`app_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`app_student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `admin_id` INT NOT NULL,
  `course_id` INT NULL DEFAULT NULL,
  `session_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `admin_id` (`admin_id` ASC) VISIBLE,
  INDEX `app_student_course_id_f414078e_fk_app_course_id` (`course_id` ASC) VISIBLE,
  INDEX `app_student_session_id_fe997916_fk_app_session_id` (`session_id` ASC) VISIBLE,
  CONSTRAINT `app_student_admin_id_47790652_fk_app_customuser_id`
    FOREIGN KEY (`admin_id`)
    REFERENCES `student_management_database`.`app_customuser` (`id`),
  CONSTRAINT `app_student_course_id_f414078e_fk_app_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `student_management_database`.`app_course` (`id`),
  CONSTRAINT `app_student_session_id_fe997916_fk_app_session_id`
    FOREIGN KEY (`session_id`)
    REFERENCES `student_management_database`.`app_session` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`app_attendancereport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`app_attendancereport` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` TINYINT(1) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `attendance_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `app_attendancereport_attendance_id_67de00ed_fk_app_attendance_id` (`attendance_id` ASC) VISIBLE,
  INDEX `app_attendancereport_student_id_2dcdf4af_fk_app_student_id` (`student_id` ASC) VISIBLE,
  CONSTRAINT `app_attendancereport_attendance_id_67de00ed_fk_app_attendance_id`
    FOREIGN KEY (`attendance_id`)
    REFERENCES `student_management_database`.`app_attendance` (`id`),
  CONSTRAINT `app_attendancereport_student_id_2dcdf4af_fk_app_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `student_management_database`.`app_student` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`auth_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`app_customuser_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`app_customuser_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customuser_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `app_customuser_groups_customuser_id_group_id_a5a0ca22_uniq` (`customuser_id` ASC, `group_id` ASC) VISIBLE,
  INDEX `app_customuser_groups_group_id_47e49ebd_fk_auth_group_id` (`group_id` ASC) VISIBLE,
  CONSTRAINT `app_customuser_group_customuser_id_164d073f_fk_app_custo`
    FOREIGN KEY (`customuser_id`)
    REFERENCES `student_management_database`.`app_customuser` (`id`),
  CONSTRAINT `app_customuser_groups_group_id_47e49ebd_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `student_management_database`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`django_content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`django_content_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label` ASC, `model` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`auth_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`auth_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC) VISIBLE,
  CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `student_management_database`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 89
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`app_customuser_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`app_customuser_user_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customuser_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `app_customuser_user_perm_customuser_id_permission_22e31019_uniq` (`customuser_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `app_customuser_user__permission_id_c5920c75_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `app_customuser_user__customuser_id_4bcbaafb_fk_app_custo`
    FOREIGN KEY (`customuser_id`)
    REFERENCES `student_management_database`.`app_customuser` (`id`),
  CONSTRAINT `app_customuser_user__permission_id_c5920c75_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `student_management_database`.`auth_permission` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`app_feedbackstaff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`app_feedbackstaff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `feedback` LONGTEXT NOT NULL,
  `reply` LONGTEXT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `app_feedbackstaff_staff_id_cb7c4c37_fk_app_staff_id` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `app_feedbackstaff_staff_id_cb7c4c37_fk_app_staff_id`
    FOREIGN KEY (`staff_id`)
    REFERENCES `student_management_database`.`app_staff` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`app_feedbackstudent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`app_feedbackstudent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `feedback` LONGTEXT NOT NULL,
  `reply` LONGTEXT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `app_feedbackstudent_student_id_01d79f5e_fk_app_student_id` (`student_id` ASC) VISIBLE,
  CONSTRAINT `app_feedbackstudent_student_id_01d79f5e_fk_app_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `student_management_database`.`app_student` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`app_leavereportstaff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`app_leavereportstaff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(60) NOT NULL,
  `message` LONGTEXT NOT NULL,
  `status` SMALLINT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `app_leavereportstaff_staff_id_c1096499_fk_app_staff_id` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `app_leavereportstaff_staff_id_c1096499_fk_app_staff_id`
    FOREIGN KEY (`staff_id`)
    REFERENCES `student_management_database`.`app_staff` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`app_leavereportstudent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`app_leavereportstudent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(60) NOT NULL,
  `message` LONGTEXT NOT NULL,
  `status` SMALLINT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `app_leavereportstudent_student_id_5406e468_fk_app_student_id` (`student_id` ASC) VISIBLE,
  CONSTRAINT `app_leavereportstudent_student_id_5406e468_fk_app_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `student_management_database`.`app_student` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`app_notificationstaff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`app_notificationstaff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` LONGTEXT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `app_notificationstaff_staff_id_5a0008af_fk_app_staff_id` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `app_notificationstaff_staff_id_5a0008af_fk_app_staff_id`
    FOREIGN KEY (`staff_id`)
    REFERENCES `student_management_database`.`app_staff` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`app_notificationstudent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`app_notificationstudent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` LONGTEXT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `app_notificationstudent_student_id_44e74323_fk_app_student_id` (`student_id` ASC) VISIBLE,
  CONSTRAINT `app_notificationstudent_student_id_44e74323_fk_app_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `student_management_database`.`app_student` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`app_studentresult`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`app_studentresult` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `test` DOUBLE NOT NULL,
  `exam` DOUBLE NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `student_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `app_studentresult_student_id_c0439bd2_fk_app_student_id` (`student_id` ASC) VISIBLE,
  INDEX `app_studentresult_subject_id_3e3ecf78_fk_app_subject_id` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `app_studentresult_student_id_c0439bd2_fk_app_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `student_management_database`.`app_student` (`id`),
  CONSTRAINT `app_studentresult_subject_id_3e3ecf78_fk_app_subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `student_management_database`.`app_subject` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`auth_group_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`auth_group_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `student_management_database`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `student_management_database`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`auth_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`auth_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`auth_user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`auth_user_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_groups_user_id_group_id_94350c0c_uniq` (`user_id` ASC, `group_id` ASC) VISIBLE,
  INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` (`group_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `student_management_database`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `student_management_database`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`auth_user_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`auth_user_user_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` (`user_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `student_management_database`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `student_management_database`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`django_admin_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`django_admin_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME(6) NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `django_admin_log_content_type_id_c4bce8eb_fk_django_co` (`content_type_id` ASC) VISIBLE,
  INDEX `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `student_management_database`.`django_content_type` (`id`),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `student_management_database`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`django_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`django_migrations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `student_management_database`.`django_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `student_management_database`.`django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`session_key`),
  INDEX `django_session_expire_date_a5c62663` (`expire_date` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
